apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwp-deployment
  labels:
    app: wwp
spec:
  replicas: 2

  selector:
    matchLabels:
      app: wwp

  template:
    metadata:
      labels:
        app: wwp

    spec:
      containers:
      - name: wwp-container
        image: kirangangadhar12/wwp-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
